### ISSUE TITLE
What license is?

### ISSUE THREAD

**Issue by ghost** [e-Mole/m-Bitbeam_Parts_for_LDraw#1]
`LICENSE` file is *GNU GPLv2* license

- https://github.com/e-Mole/m-Bitbeam_Parts_for_LDraw/blob/master/LICENSE

In same time inside `README.md` file you claim that license is *CC-NC-SA 4.0*

- https://github.com/e-Mole/m-Bitbeam_Parts_for_LDraw/blob/master/README.md

So, what license to use?

**Comment by e-Mole** [comment]
License is CC-NC-SA 4.0
